# Generated by Django 4.1.7 on 2023-09-29 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_type', models.CharField(default='New', max_length=120)),
                ('registration_no', models.CharField(blank=True, default='2947388', max_length=120, null=True)),
                ('name', models.CharField(max_length=120)),
                ('arabic_name', models.CharField(blank=True, max_length=120, null=True)),
                ('date_of_birth', models.CharField(blank=True, default='14/12/2022', max_length=100, null=True)),
                ('nationality', models.CharField(default='Oman', max_length=120)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=100)),
                ('passport_no', models.CharField(default='B00806552', max_length=120)),
                ('civil_id', models.CharField(blank=True, default='128240750', max_length=120, null=True)),
                ('sponsor', models.CharField(default='////////', max_length=120)),
                ('category', models.CharField(default='Employment (labour card & Resident card)', max_length=200)),
                ('validity_of_the_medical', models.CharField(default='21/11/2022', max_length=120)),
                ('to', models.CharField(default='21/12/2022', max_length=120)),
                ('medical_center', models.CharField(default='BADR AL SAMAA HOSPITAL - SALALAH', max_length=120)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='images/QR_CODE')),
            ],
        ),
    ]
